# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_rand_gen_host <- function(n, seed = 0L) {
    .Call(`_fastbootstrap_test_rand_gen_host`, n, seed)
}

